name = "Dot-Org"
license = "MIT"
licenselink = "https://github.com/cncf/dot-org-hugo-theme/blob/main/LICENSE"
description = "This modern, accesible, performant theme is ideal for powering the website of a small organization"
homepage = "https://todogroup.org/"
demosite = ""
min_version = "0.110.0"
theme_version = "1.0.0"

tags = [
  "performance",
  "accessibility",
  "multilingual",
  "responsive"
]

features = [
  "Multilingual"
]

[author]
  name = "CNCF"
  homepage = "https://www.cncf.io/"
